# LCS

The least common subsequence problem is a fundamental one in computer science. The problem statement is simple, if somewhat abstract: a common subsequence is the character orderings in two strings that may not be perfectly aligned.

For instance, imagine I have string s1 = 1a2b3c and string s2 = 7a8b9c

By deleting 1,2, and 3 from s1 and 7, 8, and 9 from s2 I have the longest common subsequence: abc.

In most LCS tutorials, the two strings are provided first and the longest common subsequence is calculated from them. In this notebook we do something different; we start with the LCS string first, randomly obfuscate it, and then use the algorithm to rediscover it.

In [38]:
# Let's work backwards and generate our Longest Common Subsequence before we do anything else.
# Feel free to change this value

secret = "I am the walrus"

The opposite of removing non-matching characters from a string is adding non-matching characters from a string.
Here we create a character range:

In [39]:
charRange = set(map(lambda x: chr(x), range(20, 126)))

print(charRange)

{'7', '(', ';', '>', ' ', '[', 'F', 'T', 'O', 'c', 'J', 'b', '*', 'i', '\\', 'e', 'A', ')', '0', 'N', '\x1a', '\x18', '.', 'S', '{', '/', 'o', 'n', '\x15', 't', 'z', '3', 'Z', '2', 'y', '#', '1', '\x1e', '9', 'd', 'p', '\x17', '!', '+', '`', 'R', 'k', '"', '-', '$', '\x14', '\x1b', '<', '4', 'G', 'j', 'B', 'I', '5', '?', ']', '\x1d', 'v', '%', 'M', "'", 'X', '\x19', 'q', 'u', '\x16', 'D', 'f', 'W', '^', '@', '&', 'w', 'a', 'h', 'C', 'Q', 'Y', '\x1f', '\x1c', 'U', ',', 'm', 'K', '6', '_', 'H', 'L', 'V', 'r', '8', ':', 'E', 's', 'g', '|', 'x', '}', '=', 'P', 'l'}


In [40]:
import random

s1 = ""
s2 = ""

# copy the initial character range into a new set (shallow copy)
possibilities = charRange.copy() 

for char in secret:
    
    # using discard instead of remove because remove will throw an error if the key doesn't already exist
    possibilities.discard(char)
    
    # add a random character that hasn't been added before. Do it between 0 and 5 times.
    for i in range(0, random.randint(0,5)):
        filler = random.sample(possibilities, 1)[0]
        possibilities.remove(filler)
        s1 += filler
        
    for i in range(0, random.randint(0,5)):
        filler = random.sample(possibilities, 1)[0]
        possibilities.remove(filler)
        s2 += filler
        
    s1 += char
    s2 += char
        
print(s1)
print(s2)

I_d aNZWm Mt5qHh!/^pAe%: wR=.-a?clB]rEf2u+9s
o*I $0J&Cam ythVe D)zw`SYagXTljnbrQus


Now we create an array that's of dimensions [s1 + 1, s2 + 1]

In [41]:
import numpy as np

m = len(s1)
n = len(s2)

x = np.zeros([m + 1, n + 1])

Iterate over the strings and count how many times matches have occurred


In [42]:

for i in range(1, m +1): 
    #print(x[i - 1][j-1])
    for j in range(1, n + 1):
        if s1[i - 1] == s2[j - 1]:
            x[i][j] = 1 + x[i - 1][j - 1]
            #print(s1[i])
        else:
            x[i][j] = max(x[i - 1][j], x[i][j - 1])
            
print(x)
            

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  1.  1.  1.]
 ...
 [ 0.  0.  0. ... 13. 14. 14.]
 [ 0.  0.  0. ... 13. 14. 14.]
 [ 0.  0.  0. ... 13. 14. 15.]]


In [43]:
i = m
j = n

reconstruction = ''

while i > 0 and j > 0:

    x[i][j] += 0.000001
    if s1[i - 1] == s2[j-1]:
        reconstruction = (s1[i-1]) + reconstruction
    if x[i - 1][j] > x[i][j - 1]:
        i -= 1
    else:
        j -= 1

print(reconstruction)

I am the walrus
